test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  database: donnadonna
  username: root
  password: 12345678

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  database: donnadonna
  username: root
  password: 12345678

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  database: donnadonna
  username: root
  password: 12345678
